# Generated by Django 2.1 on 2018-08-03 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('offerid', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('packageid', models.IntegerField()),
                ('netwok', models.CharField(max_length=140)),
                ('packageDesc', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='SimCard',
            fields=[
                ('simid', models.AutoField(primary_key=True, serialize=False)),
                ('serial', models.CharField(db_index=True, max_length=20)),
                ('passport', models.CharField(blank=True, db_index=True, default='', max_length=12)),
                ('nationality', models.CharField(blank=True, default='', max_length=140)),
                ('phone', models.CharField(max_length=12)),
                ('original_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activated', models.BooleanField(blank=True, default=False)),
                ('time_activate', models.DateTimeField(blank=True, null=True)),
                ('fingerprint', models.BinaryField(blank=True, null=True)),
                ('time_enrol', models.DateTimeField(blank=True, null=True)),
                ('offerid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cell.Offer')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=140)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('password', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=12)),
                ('campaign_name', models.CharField(max_length=30)),
                ('usertype', models.IntegerField(db_index=True)),
            ],
        ),
        migrations.AddField(
            model_name='simcard',
            name='userid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cell.User'),
        ),
    ]
