# Generated by Django 2.1 on 2018-08-03 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cell', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='netwok',
            new_name='network',
        ),
    ]
